{
 "title": "Performance Metrics Provisioned",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (CPU001)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu-perf-metrics",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User %" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System %" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle %" ], "type": "alias" }
      ],
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wait %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpus", "operator": "=", "value": "CPU001" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (CPU002)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu-perf-metrics",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User %" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System %" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle %" ], "type": "alias" }
      ],
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wait %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpus", "operator": "=", "value": "CPU002" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (CPU003)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu-perf-metrics",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User %" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System %" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle %" ], "type": "alias" }
      ],
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wait %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpus", "operator": "=", "value": "CPU003" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (CPU004)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu-perf-metrics",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User %" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System %" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle %" ], "type": "alias" }
      ],
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wait %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpus", "operator": "=", "value": "CPU004" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (CPU005)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu-perf-metrics",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User %" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System %" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle %" ], "type": "alias" }
      ],
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wait %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpus", "operator": "=", "value": "CPU005" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (CPU006)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu-perf-metrics",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User %" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System %" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle %" ], "type": "alias" }
      ],
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wait %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpus", "operator": "=", "value": "CPU006" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (CPU007)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu-perf-metrics",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User %" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System %" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle %" ], "type": "alias" }
      ],
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wait %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpus", "operator": "=", "value": "CPU007" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (CPU008)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu-perf-metrics",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User %" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System %" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle %" ], "type": "alias" }
      ],
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wait %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpus", "operator": "=", "value": "CPU008" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (CPU009)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu-perf-metrics",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User %" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System %" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle %" ], "type": "alias" }
      ],
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wait %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpus", "operator": "=", "value": "CPU009" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (CPU010)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu-perf-metrics",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User %" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System %" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle %" ], "type": "alias" }
      ],
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wait %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpus", "operator": "=", "value": "CPU010" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (CPU011)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu-perf-metrics",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User %" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System %" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle %" ], "type": "alias" }
      ],
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wait %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpus", "operator": "=", "value": "CPU011" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (CPU012)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu-perf-metrics",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "User %" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "System %" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Idle %" ], "type": "alias" }
      ],
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wait %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cpus", "operator": "=", "value": "CPU012" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO (Read)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk-perf-metrics",
     "query": "SELECT mean(\"cached\") FROM \"autogen\".\"mem-perf-metrics\" WHERE $timeFilter GROUP BY time(1s) tz('MSK')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Read, Kb/s" ], "type": "alias" }
      ]
     ],
     "tz": "Europe/Moscow"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem-perf-metrics",
     "query": "SELECT mean(\"memtotal\") AS \"Total Memory, Gb\", mean(\"active\") AS \"Active Memory, Gb\" FROM \"autogen\".\"mem-perf-metrics\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memtotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total Memory" ], "type": "alias" }
      ],
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Active Memory" ], "type": "alias" }
      ],
      [
       { "params": [ "buffers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Buffered" ], "type": "alias" }
      ],
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Free" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}